# Generated by Django 2.2.3 on 2019-10-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='Message',
            new_name='message',
        ),
    ]
